<?php

use App\Http\Controllers\Backend\AnalyticScriptController;
use App\Http\Controllers\Backend\AttributeController;
use App\Http\Controllers\Backend\BannerController;
use App\Http\Controllers\Backend\BlogCategoryController;
use App\Http\Controllers\Backend\BlogController;
use App\Http\Controllers\Backend\BrandController;
use App\Http\Controllers\Backend\BusinessSettingController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\ColorController;
use App\Http\Controllers\Backend\ContactController;
use App\Http\Controllers\Backend\CouponController;
use App\Http\Controllers\Backend\CurrencyController;
use App\Http\Controllers\Backend\CustomerController;
use App\Http\Controllers\Backend\DealOfTheDayController;
use App\Http\Controllers\Backend\DeliveryZoneController;
use App\Http\Controllers\Backend\EmailTemplateController;
use App\Http\Controllers\Backend\FaqController;
use App\Http\Controllers\Backend\FeatureDealController;
use App\Http\Controllers\Backend\FlashDealController;
use App\Http\Controllers\Backend\GiftCardController;
use App\Http\Controllers\Backend\HelpTopicController;
use App\Http\Controllers\Backend\JobOpeningController;
use App\Http\Controllers\Backend\LoyaltyTierController;
use App\Http\Controllers\Backend\MaterialController;
use App\Http\Controllers\Backend\MostDemandedController;
use App\Http\Controllers\Backend\NewsletterSubscriberController;
use App\Http\Controllers\Backend\OfflinePaymentMethodController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Backend\PageController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\ProductImageController;
use App\Http\Controllers\Backend\RefundRequestController;
use App\Http\Controllers\Backend\ReturnPolicyController;
use App\Http\Controllers\Backend\ReviewController;
use App\Http\Controllers\Backend\SearchFunctionController;
use App\Http\Controllers\Backend\ShippingAddressController;
use App\Http\Controllers\Backend\ShippingMethodController;
use App\Http\Controllers\Backend\SizeController;
use App\Http\Controllers\Backend\SocialMediaController;
use App\Http\Controllers\Backend\SoftCredentialController;
use App\Http\Controllers\Backend\StockClearanceSetupController;
use App\Http\Controllers\Backend\StoreLocationController;
use App\Http\Controllers\Backend\SupplierController;
use App\Http\Controllers\Backend\SupportTicketController;
use App\Http\Controllers\Backend\TagController;
use App\Http\Controllers\Backend\TaxRateController;
use App\Http\Controllers\Backend\TeamMemberController;
use App\Http\Controllers\Backend\TestimonialController;
use App\Http\Controllers\Backend\WarehouseController;
use App\Http\Controllers\Backend\WishlistController;
use Illuminate\Support\Facades\Route;

Route::inertia('/', 'Welcome')->name('home');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::inertia('dashboard', 'Dashboard')->name('dashboard');

    Route::resource('attributes', AttributeController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::resource('colors', ColorController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::resource('sizes', SizeController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::resource('materials', MaterialController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::resource('brands', BrandController::class)->except(['show']);
    Route::resource('banners', BannerController::class)->except(['show']);
    Route::resource('tags', TagController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::resource('currencies', CurrencyController::class)->except(['show']);
    Route::resource('customers', CustomerController::class)->except(['show']);
    Route::resource('categories', CategoryController::class)->except(['show']);
    Route::resource('blog-categories', BlogCategoryController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::resource('blogs', BlogController::class)->except(['show']);
    Route::resource('help-topics', HelpTopicController::class)->except(['show']);
    Route::resource('shipping-methods', ShippingMethodController::class)->except(['show']);
    Route::resource('shipping-addresses', ShippingAddressController::class)->except(['show']);
    Route::resource('search-functions', SearchFunctionController::class)->except(['show']);
    Route::resource('offline-payment-methods', OfflinePaymentMethodController::class)->except(['show']);
    Route::resource('social-medias', SocialMediaController::class)->except(['show']);
    Route::resource('credentials', SoftCredentialController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::resource('testimonials', TestimonialController::class)->except(['show']);
    Route::resource('faqs', FaqController::class)->except(['show']);
    Route::resource('coupons', CouponController::class)->except(['show']);
    Route::resource('newsletter-subscribers', NewsletterSubscriberController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::resource('tax-rates', TaxRateController::class)->except(['show']);
    Route::resource('warehouses', WarehouseController::class)->except(['show']);
    Route::resource('return-policies', ReturnPolicyController::class)->except(['show']);
    Route::resource('suppliers', SupplierController::class)->except(['show']);
    Route::resource('pages', PageController::class)->except(['show']);
    Route::resource('store-locations', StoreLocationController::class)->except(['show']);
    Route::resource('gift-cards', GiftCardController::class)->except(['show']);
    Route::resource('team-members', TeamMemberController::class)->except(['show']);
    Route::resource('loyalty-tiers', LoyaltyTierController::class)->except(['show']);
    Route::resource('job-openings', JobOpeningController::class)->except(['show']);
    Route::resource('analytic-scripts', AnalyticScriptController::class)->except(['show']);
    Route::resource('delivery-zones', DeliveryZoneController::class)->except(['show']);
    Route::resource('products', ProductController::class)->except(['show']);
    Route::resource('products.images', ProductImageController::class)->shallow()->only(['store', 'destroy']);
    Route::resource('orders', OrderController::class)->except(['show']);
    Route::resource('reviews', ReviewController::class)->except(['show']);
    Route::resource('wishlists', WishlistController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::resource('contacts', ContactController::class)->except(['show']);
    Route::resource('support-tickets', SupportTicketController::class)->except(['show']);
    Route::resource('email-templates', EmailTemplateController::class)->except(['show']);
    Route::resource('flash-deals', FlashDealController::class)->except(['show']);
    Route::resource('feature-deals', FeatureDealController::class)->except(['show']);
    Route::resource('stock-clearance-setups', StockClearanceSetupController::class)->except(['show']);
    Route::resource('deal-of-the-days', DealOfTheDayController::class)->except(['show']);
    Route::resource('most-demandeds', MostDemandedController::class)->except(['show']);
    Route::resource('refund-requests', RefundRequestController::class)->except(['show']);

    Route::get('business-settings', [BusinessSettingController::class, 'edit'])->name('business-settings.edit');
    Route::patch('business-settings', [BusinessSettingController::class, 'update'])->name('business-settings.update');
});

require __DIR__.'/settings.php';
