CREATE TABLE IF NOT EXISTS `roles` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(30) NOT NULL DEFAULT NULL,
	`module_access` VARCHAR(250) NOT NULL DEFAULT NULL,
	`status` TINYINT NOT NULL DEFAULT 1,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `users` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(80) NOT NULL DEFAULT NULL,
	`phone` VARCHAR(25) NOT NULL DEFAULT NULL,
	`image` VARCHAR(30) NOT NULL DEFAULT 'def.png',
	`identify_image` TEXT NOT NULL,
	`identify_type` VARCHAR(255) NOT NULL DEFAULT NULL,
	`identify_number` INTEGER NOT NULL DEFAULT NULL,
	`email` VARCHAR(80) NOT NULL,
	`email_verified_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`password` VARCHAR(80) NOT NULL,
	`remember_token` VARCHAR(100) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`status` TINYINT NOT NULL DEFAULT 1,
	PRIMARY KEY(`id`),
	CONSTRAINT `admins_email_unique` UNIQUE (`email`)
);


CREATE TABLE IF NOT EXISTS `analytic_scripts` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`type` VARCHAR(255) NOT NULL DEFAULT NULL,
	`script_id` TEXT NOT NULL,
	`script` LONGTEXT NOT NULL,
	`is_active` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `attachments` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`attachable_type` VARCHAR(191) NOT NULL,
	`attachable_id` BIGINT NOT NULL,
	`file_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`file_name` VARCHAR(191) NOT NULL DEFAULT NULL,
	`storage_disk` VARCHAR(191) NOT NULL DEFAULT 'public',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `attributes` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `authors` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `banners` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`photo` VARCHAR(255) NOT NULL DEFAULT NULL,
	`banner_type` VARCHAR(255) NOT NULL,
	`theme` VARCHAR(255) NOT NULL DEFAULT 'default',
	`published` INTEGER NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`url` VARCHAR(255) NOT NULL DEFAULT NULL,
	`resource_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`resource_id` BIGINT NOT NULL DEFAULT NULL,
	`title` VARCHAR(191) NOT NULL DEFAULT NULL,
	`sub_title` VARCHAR(191) NOT NULL DEFAULT NULL,
	`button_text` VARCHAR(191) NOT NULL DEFAULT NULL,
	`background_color` VARCHAR(191) NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `billing_addresses` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`customer_id` BIGINT NOT NULL DEFAULT NULL,
	`contact_person_name` VARCHAR(191) NOT NULL DEFAULT NULL,
	`address_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`address` VARCHAR(191) NOT NULL DEFAULT NULL,
	`city` VARCHAR(191) NOT NULL DEFAULT NULL,
	`zip` VARCHAR(191) NOT NULL DEFAULT NULL,
	`phone` VARCHAR(191) NOT NULL DEFAULT NULL,
	`state` VARCHAR(191) NOT NULL DEFAULT NULL,
	`country` VARCHAR(191) NOT NULL DEFAULT NULL,
	`latitude` VARCHAR(191) NOT NULL DEFAULT NULL,
	`longitude` VARCHAR(191) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `blog_categories` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`slug` MEDIUMTEXT NOT NULL,
	`status` TINYINT NOT NULL DEFAULT 1,
	`click_count` INTEGER NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`),
	CONSTRAINT `blog_categories_name_unique` UNIQUE (`name`)
);


CREATE TABLE IF NOT EXISTS `blog_seos` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`blog_id` INTEGER NOT NULL,
	`title` VARCHAR(255) NOT NULL DEFAULT NULL,
	`description` VARCHAR(255) NOT NULL DEFAULT NULL,
	`index` VARCHAR(255) NOT NULL DEFAULT NULL,
	`no_follow` VARCHAR(255) NOT NULL DEFAULT NULL,
	`no_image_index` VARCHAR(255) NOT NULL DEFAULT NULL,
	`no_archive` VARCHAR(255) NOT NULL DEFAULT NULL,
	`no_snippet` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_snippet` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_snippet_value` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_video_preview` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_video_preview_value` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_image_preview` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_image_preview_value` VARCHAR(255) NOT NULL DEFAULT NULL,
	`image` VARCHAR(255) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `blog_translations` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`translation_type` VARCHAR(255) NOT NULL,
	`translation_id` BIGINT NOT NULL,
	`locale` VARCHAR(255) NOT NULL,
	`key` VARCHAR(255) NOT NULL DEFAULT NULL,
	`value` TEXT NOT NULL,
	`is_draft` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `blogs` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`slug` MEDIUMTEXT NOT NULL,
	`readable_id` VARCHAR(255) NOT NULL,
	`category_id` BIGINT NOT NULL DEFAULT NULL,
	`writer` VARCHAR(255) NOT NULL DEFAULT NULL,
	`title` VARCHAR(255) NOT NULL,
	`description` LONGTEXT NOT NULL,
	`image` VARCHAR(255) NOT NULL DEFAULT NULL,
	`image_storage_type` VARCHAR(15) NOT NULL DEFAULT 'public',
	`draft_image` VARCHAR(255) NOT NULL DEFAULT NULL,
	`draft_image_storage_type` VARCHAR(15) NOT NULL DEFAULT 'public',
	`publish_date` DATETIME NOT NULL DEFAULT '2025-02-13 14:40:55',
	`is_published` TINYINT NOT NULL DEFAULT 0,
	`status` TINYINT NOT NULL DEFAULT 0,
	`is_draft` TINYINT NOT NULL DEFAULT 0,
	`draft_data` TEXT NOT NULL,
	`click_count` INTEGER NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `brands` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL DEFAULT NULL,
	`image` VARCHAR(50) NOT NULL DEFAULT 'def.png',
	`image_storage_type` VARCHAR(10) NOT NULL DEFAULT 'public',
	`image_alt_text` VARCHAR(255) NOT NULL DEFAULT NULL,
	`status` TINYINT NOT NULL DEFAULT 1,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `business_pages` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(191) NOT NULL,
	`slug` VARCHAR(191) NOT NULL,
	`description` LONGTEXT NOT NULL,
	`status` TINYINT NOT NULL DEFAULT 0,
	`default_status` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `business_settings` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`type` VARCHAR(50) NOT NULL,
	`value` LONGTEXT NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `cart_shippings` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`cart_group_id` VARCHAR(191) NOT NULL DEFAULT NULL,
	`shipping_method_id` BIGINT NOT NULL DEFAULT NULL,
	`shipping_cost` DOUBLE(8,2) NOT NULL DEFAULT 0.00,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `carts` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`customer_id` BIGINT NOT NULL DEFAULT NULL,
	`cart_group_id` VARCHAR(191) NOT NULL DEFAULT NULL,
	`product_id` BIGINT NOT NULL DEFAULT NULL,
	`product_type` VARCHAR(20) NOT NULL DEFAULT 'physical',
	`digital_product_type` VARCHAR(30) NOT NULL DEFAULT NULL,
	`color` VARCHAR(191) NOT NULL DEFAULT NULL,
	`choices` TEXT NOT NULL,
	`variations` TEXT NOT NULL,
	`variant` TEXT NOT NULL,
	`quantity` INTEGER NOT NULL DEFAULT 1,
	`price` DOUBLE NOT NULL DEFAULT 1,
	`tax` DOUBLE NOT NULL DEFAULT 1,
	`discount` DOUBLE NOT NULL DEFAULT 1,
	`tax_model` VARCHAR(20) NOT NULL DEFAULT 'exclude',
	`is_checked` TINYINT NOT NULL DEFAULT 0,
	`slug` VARCHAR(191) NOT NULL DEFAULT NULL,
	`name` VARCHAR(191) NOT NULL DEFAULT NULL,
	`thumbnail` VARCHAR(191) NOT NULL DEFAULT NULL,
	`seller_id` BIGINT NOT NULL DEFAULT NULL,
	`seller_is` VARCHAR(191) NOT NULL DEFAULT 'admin',
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`shop_info` VARCHAR(191) NOT NULL DEFAULT NULL,
	`shipping_cost` DOUBLE(8,2) NOT NULL DEFAULT NULL,
	`shipping_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`is_guest` TINYINT NOT NULL DEFAULT 0,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `categories` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`slug` VARCHAR(100) NOT NULL,
	`icon` VARCHAR(250) NOT NULL DEFAULT NULL,
	`icon_storage_type` VARCHAR(10) NOT NULL DEFAULT 'public',
	`parent_id` INTEGER NOT NULL,
	`position` INTEGER NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`home_status` TINYINT NOT NULL DEFAULT 0,
	`priority` INTEGER NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `chattings` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT NOT NULL DEFAULT NULL,
	`seller_id` BIGINT NOT NULL DEFAULT NULL,
	`admin_id` BIGINT NOT NULL DEFAULT NULL,
	`delivery_man_id` BIGINT NOT NULL DEFAULT NULL,
	`message` TEXT NOT NULL,
	`attachment` LONGTEXT NOT NULL,
	`sent_by_customer` TINYINT NOT NULL DEFAULT 0,
	`sent_by_seller` TINYINT NOT NULL DEFAULT 0,
	`sent_by_admin` TINYINT NOT NULL DEFAULT NULL,
	`sent_by_delivery_man` TINYINT NOT NULL DEFAULT NULL,
	`seen_by_customer` TINYINT NOT NULL DEFAULT 1,
	`seen_by_seller` TINYINT NOT NULL DEFAULT 1,
	`seen_by_admin` TINYINT NOT NULL DEFAULT NULL,
	`seen_by_delivery_man` TINYINT NOT NULL DEFAULT NULL,
	`status` TINYINT NOT NULL DEFAULT 1,
	`notification_receiver` VARCHAR(20) NOT NULL DEFAULT NULL COMMENT 'admin, seller, customer, deliveryman',
	`seen_notification` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`shop_id` BIGINT NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `colors` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(30) NOT NULL DEFAULT NULL,
	`code` VARCHAR(10) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `contacts` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(191) NOT NULL DEFAULT NULL,
	`email` VARCHAR(191) NOT NULL DEFAULT NULL,
	`mobile_number` VARCHAR(191) NOT NULL,
	`subject` VARCHAR(191) NOT NULL,
	`message` TEXT NOT NULL,
	`seen` TINYINT NOT NULL DEFAULT 0,
	`feedback` VARCHAR(191) NOT NULL DEFAULT '0',
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`reply` LONGTEXT NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `coupons` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`added_by` VARCHAR(191) NOT NULL DEFAULT 'admin',
	`coupon_type` VARCHAR(50) NOT NULL DEFAULT NULL,
	`coupon_bearer` VARCHAR(191) NOT NULL DEFAULT 'inhouse',
	`seller_id` BIGINT NOT NULL DEFAULT NULL COMMENT 'NULL=in-house, 0=all seller',
	`customer_id` BIGINT NOT NULL DEFAULT NULL COMMENT '0 = all customer',
	`title` VARCHAR(100) NOT NULL DEFAULT NULL,
	`code` VARCHAR(15) NOT NULL DEFAULT NULL,
	`start_date` DATE NOT NULL DEFAULT NULL,
	`expire_date` DATE NOT NULL DEFAULT NULL,
	`min_purchase` DECIMAL(18,12) NOT NULL DEFAULT 0.000000000000,
	`max_discount` DECIMAL(18,12) NOT NULL DEFAULT 0.000000000000,
	`discount` DECIMAL(18,12) NOT NULL DEFAULT 0.000000000000,
	`discount_type` VARCHAR(15) NOT NULL DEFAULT 'percentage',
	`status` TINYINT NOT NULL DEFAULT 1,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`limit` INTEGER NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `currencies` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(191) NOT NULL,
	`symbol` VARCHAR(191) NOT NULL,
	`code` VARCHAR(191) NOT NULL,
	`exchange_rate` VARCHAR(191) NOT NULL,
	`status` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `customer_wallet_histories` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`customer_id` BIGINT NOT NULL DEFAULT NULL,
	`transaction_amount` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
	`transaction_type` VARCHAR(20) NOT NULL DEFAULT NULL,
	`transaction_method` VARCHAR(30) NOT NULL DEFAULT NULL,
	`transaction_id` VARCHAR(20) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `customer_wallets` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`customer_id` BIGINT NOT NULL DEFAULT NULL,
	`balance` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
	`royality_points` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `deal_of_the_days` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(150) NOT NULL DEFAULT NULL,
	`product_id` BIGINT NOT NULL DEFAULT NULL,
	`discount` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
	`discount_type` VARCHAR(12) NOT NULL DEFAULT 'amount',
	`status` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `delivery_country_codes` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`country_code` VARCHAR(191) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `delivery_histories` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`order_id` BIGINT NOT NULL DEFAULT NULL,
	`deliveryman_id` BIGINT NOT NULL DEFAULT NULL,
	`time` DATETIME NOT NULL DEFAULT NULL,
	`longitude` VARCHAR(191) NOT NULL DEFAULT NULL,
	`latitude` VARCHAR(191) NOT NULL DEFAULT NULL,
	`location` VARCHAR(191) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `delivery_man_transactions` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`delivery_man_id` BIGINT NOT NULL,
	`user_id` BIGINT NOT NULL,
	`user_type` VARCHAR(20) NOT NULL,
	`transaction_id` CHAR(36) NOT NULL,
	`debit` DECIMAL(50,2) NOT NULL DEFAULT 0.00,
	`credit` DECIMAL(50,2) NOT NULL DEFAULT 0.00,
	`transaction_type` VARCHAR(20) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `delivery_zip_codes` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`zipcode` VARCHAR(191) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `email_templates` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`template_name` VARCHAR(191) NOT NULL,
	`user_type` VARCHAR(191) NOT NULL,
	`template_design_name` VARCHAR(191) NOT NULL,
	`title` VARCHAR(191) NOT NULL DEFAULT NULL,
	`body` TEXT NOT NULL,
	`banner_image` VARCHAR(191) NOT NULL DEFAULT NULL,
	`image` VARCHAR(191) NOT NULL DEFAULT NULL,
	`logo` VARCHAR(191) NOT NULL DEFAULT NULL,
	`button_name` VARCHAR(191) NOT NULL DEFAULT NULL,
	`button_url` VARCHAR(191) NOT NULL DEFAULT NULL,
	`footer_text` VARCHAR(191) NOT NULL DEFAULT NULL,
	`copyright_text` VARCHAR(191) NOT NULL DEFAULT NULL,
	`pages` LONGTEXT NOT NULL,
	`social_media` LONGTEXT NOT NULL,
	`hide_field` LONGTEXT NOT NULL,
	`button_content_status` TINYINT NOT NULL DEFAULT 1,
	`product_information_status` TINYINT NOT NULL DEFAULT 1,
	`order_information_status` TINYINT NOT NULL DEFAULT 1,
	`status` TINYINT NOT NULL DEFAULT 1,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `emergency_contacts` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT NOT NULL,
	`name` VARCHAR(191) NOT NULL,
	`country_code` VARCHAR(20) NOT NULL DEFAULT NULL,
	`phone` VARCHAR(25) NOT NULL,
	`status` TINYINT NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `error_logs` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`status_code` INTEGER NOT NULL,
	`url` VARCHAR(255) NOT NULL,
	`hit_counts` INTEGER NOT NULL DEFAULT 0,
	`redirect_url` VARCHAR(255) NOT NULL DEFAULT NULL,
	`redirect_status` VARCHAR(255) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `feature_deals` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`url` VARCHAR(191) NOT NULL DEFAULT NULL,
	`photo` VARCHAR(191) NOT NULL DEFAULT NULL,
	`status` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `flash_deal_products` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`flash_deal_id` BIGINT NOT NULL DEFAULT NULL,
	`product_id` BIGINT NOT NULL DEFAULT NULL,
	`discount` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
	`discount_type` VARCHAR(20) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `flash_deals` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(150) NOT NULL DEFAULT NULL,
	`start_date` DATE NOT NULL DEFAULT NULL,
	`end_date` DATE NOT NULL DEFAULT NULL,
	`status` TINYINT NOT NULL DEFAULT 0,
	`featured` TINYINT NOT NULL DEFAULT 0,
	`background_color` VARCHAR(255) NOT NULL DEFAULT NULL,
	`text_color` VARCHAR(255) NOT NULL DEFAULT NULL,
	`banner` VARCHAR(100) NOT NULL DEFAULT NULL,
	`slug` VARCHAR(255) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`product_id` INTEGER NOT NULL DEFAULT NULL,
	`deal_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `guest_users` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`ip_address` VARCHAR(255) NOT NULL DEFAULT NULL,
	`fcm_token` VARCHAR(255) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `help_topics` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`type` VARCHAR(191) NOT NULL DEFAULT 'default',
	`question` TEXT NOT NULL,
	`answer` TEXT NOT NULL,
	`ranking` INTEGER NOT NULL DEFAULT 1,
	`status` TINYINT NOT NULL DEFAULT 1,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `login_setups` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`key` VARCHAR(255) NOT NULL DEFAULT NULL,
	`value` TEXT NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `loyalty_point_transactions` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT NOT NULL DEFAULT NULL,
	`transaction_id` CHAR(36) NOT NULL,
	`credit` DECIMAL(24,3) NOT NULL DEFAULT 0.000,
	`debit` DECIMAL(24,3) NOT NULL DEFAULT 0.000,
	`balance` DECIMAL(24,3) NOT NULL DEFAULT 0.000,
	`reference` VARCHAR(191) NOT NULL DEFAULT NULL,
	`transaction_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `most_demandeds` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`banner` VARCHAR(255) NOT NULL,
	`product_id` BIGINT NOT NULL,
	`status` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `notification_messages` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`user_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`key` VARCHAR(191) NOT NULL DEFAULT NULL,
	`message` TEXT NOT NULL,
	`status` TINYINT NOT NULL DEFAULT 1,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `notification_seens` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`seller_id` INTEGER NOT NULL DEFAULT NULL,
	`user_id` INTEGER NOT NULL DEFAULT NULL,
	`notification_id` INTEGER NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `notifications` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`sent_by` VARCHAR(255) NOT NULL DEFAULT 'system',
	`sent_to` VARCHAR(255) NOT NULL DEFAULT 'customer',
	`title` VARCHAR(100) NOT NULL DEFAULT NULL,
	`description` VARCHAR(191) NOT NULL DEFAULT NULL,
	`notification_count` INTEGER NOT NULL DEFAULT 0,
	`image` VARCHAR(50) NOT NULL DEFAULT NULL,
	`status` TINYINT NOT NULL DEFAULT 1,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `offline_payment_methods` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`method_name` VARCHAR(255) NOT NULL,
	`method_fields` TEXT NOT NULL,
	`method_informations` TEXT NOT NULL,
	`status` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `offline_payments` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`order_id` INTEGER NOT NULL,
	`payment_info` LONGTEXT NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `order_delivery_verifications` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`order_id` BIGINT NOT NULL,
	`image` TEXT NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `order_details` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`order_id` BIGINT NOT NULL DEFAULT NULL,
	`product_id` BIGINT NOT NULL DEFAULT NULL,
	`seller_id` BIGINT NOT NULL DEFAULT NULL,
	`digital_file_after_sell` VARCHAR(191) NOT NULL DEFAULT NULL,
	`product_details` TEXT NOT NULL,
	`qty` INTEGER NOT NULL DEFAULT 0,
	`price` DOUBLE NOT NULL DEFAULT 0,
	`tax` DOUBLE NOT NULL DEFAULT 0,
	`discount` DOUBLE NOT NULL DEFAULT 0,
	`tax_model` VARCHAR(20) NOT NULL DEFAULT 'exclude',
	`delivery_status` VARCHAR(15) NOT NULL DEFAULT 'pending',
	`payment_status` VARCHAR(15) NOT NULL DEFAULT 'unpaid',
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`shipping_method_id` BIGINT NOT NULL DEFAULT NULL,
	`variant` VARCHAR(255) NOT NULL DEFAULT NULL,
	`variation` VARCHAR(255) NOT NULL DEFAULT NULL,
	`discount_type` VARCHAR(30) NOT NULL DEFAULT NULL,
	`is_stock_decreased` TINYINT NOT NULL DEFAULT 1,
	`refund_request` INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `order_expected_delivery_histories` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`order_id` BIGINT NOT NULL,
	`user_id` BIGINT NOT NULL,
	`user_type` VARCHAR(191) NOT NULL,
	`expected_delivery_date` DATE NOT NULL,
	`cause` VARCHAR(191) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `order_status_histories` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`order_id` BIGINT NOT NULL,
	`user_id` BIGINT NOT NULL,
	`user_type` VARCHAR(191) NOT NULL,
	`status` VARCHAR(191) NOT NULL,
	`cause` VARCHAR(191) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `order_transactions` (
	`seller_id` BIGINT NOT NULL,
	`order_id` BIGINT NOT NULL,
	`order_amount` DECIMAL(50,2) NOT NULL DEFAULT 0.00,
	`seller_amount` DECIMAL(50,2) NOT NULL DEFAULT 0.00,
	`admin_commission` DECIMAL(50,2) NOT NULL DEFAULT 0.00,
	`received_by` VARCHAR(191) NOT NULL,
	`status` VARCHAR(191) NOT NULL DEFAULT NULL,
	`delivery_charge` DECIMAL(50,2) NOT NULL DEFAULT 0.00,
	`tax` DECIMAL(50,2) NOT NULL DEFAULT 0.00,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`customer_id` BIGINT NOT NULL DEFAULT NULL,
	`seller_is` VARCHAR(191) NOT NULL DEFAULT NULL,
	`delivered_by` VARCHAR(191) NOT NULL DEFAULT 'admin',
	`payment_method` VARCHAR(191) NOT NULL DEFAULT NULL,
	`transaction_id` VARCHAR(191) NOT NULL DEFAULT NULL,
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `orders` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`customer_id` VARCHAR(15) NOT NULL DEFAULT NULL,
	`is_guest` TINYINT NOT NULL DEFAULT 0,
	`customer_type` VARCHAR(10) NOT NULL DEFAULT NULL,
	`payment_status` VARCHAR(15) NOT NULL DEFAULT 'unpaid',
	`order_status` VARCHAR(50) NOT NULL DEFAULT 'pending',
	`payment_method` VARCHAR(100) NOT NULL DEFAULT NULL,
	`transaction_ref` VARCHAR(30) NOT NULL DEFAULT NULL,
	`payment_by` VARCHAR(191) NOT NULL DEFAULT NULL,
	`payment_note` TEXT NOT NULL,
	`order_amount` DOUBLE NOT NULL DEFAULT 0,
	`paid_amount` DECIMAL(18,12) NOT NULL DEFAULT 0.000000000000,
	`bring_change_amount` DECIMAL(18,12) NOT NULL DEFAULT 0.000000000000,
	`bring_change_amount_currency` VARCHAR(255) NOT NULL DEFAULT NULL,
	`admin_commission` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
	`is_pause` VARCHAR(20) NOT NULL DEFAULT '0',
	`cause` VARCHAR(191) NOT NULL DEFAULT NULL,
	`shipping_address` TEXT NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`discount_amount` DOUBLE NOT NULL DEFAULT 0,
	`discount_type` VARCHAR(30) NOT NULL DEFAULT NULL,
	`coupon_code` VARCHAR(191) NOT NULL DEFAULT NULL,
	`coupon_discount_bearer` VARCHAR(191) NOT NULL DEFAULT 'inhouse',
	`shipping_responsibility` VARCHAR(255) NOT NULL DEFAULT NULL,
	`shipping_method_id` BIGINT NOT NULL DEFAULT 0,
	`shipping_cost` DOUBLE(8,2) NOT NULL DEFAULT 0.00,
	`is_shipping_free` TINYINT NOT NULL DEFAULT 0,
	`order_group_id` VARCHAR(191) NOT NULL DEFAULT 'def-order-group',
	`verification_code` VARCHAR(191) NOT NULL DEFAULT '0',
	`verification_status` TINYINT NOT NULL DEFAULT 0,
	`seller_id` BIGINT NOT NULL DEFAULT NULL,
	`seller_is` VARCHAR(191) NOT NULL DEFAULT NULL,
	`shipping_address_data` TEXT NOT NULL,
	`delivery_man_id` BIGINT NOT NULL DEFAULT NULL,
	`deliveryman_charge` DOUBLE NOT NULL DEFAULT 0,
	`expected_delivery_date` DATE NOT NULL DEFAULT NULL,
	`order_note` TEXT NOT NULL,
	`billing_address` BIGINT NOT NULL DEFAULT NULL,
	`billing_address_data` TEXT NOT NULL,
	`order_type` VARCHAR(191) NOT NULL DEFAULT 'default_type',
	`extra_discount` DOUBLE(8,2) NOT NULL DEFAULT 0.00,
	`extra_discount_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`refer_and_earn_discount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	`free_delivery_bearer` VARCHAR(255) NOT NULL DEFAULT NULL,
	`checked` TINYINT NOT NULL DEFAULT 0,
	`shipping_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`delivery_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`delivery_service_name` VARCHAR(191) NOT NULL DEFAULT NULL,
	`third_party_delivery_tracking_id` VARCHAR(191) NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `password_resets` (
	`identity` VARCHAR(191) NOT NULL,
	`token` VARCHAR(191) NOT NULL,
	`otp_hit_count` TINYINT NOT NULL DEFAULT 0,
	`is_temp_blocked` TINYINT NOT NULL DEFAULT 0,
	`temp_block_time` TIMESTAMP NOT NULL DEFAULT NULL,
	`expires_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`user_type` VARCHAR(191) NOT NULL DEFAULT 'customer',
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `payment_requests` (
	`id` CHAR(36) NOT NULL,
	`payer_id` VARCHAR(64) NOT NULL DEFAULT NULL,
	`receiver_id` VARCHAR(64) NOT NULL DEFAULT NULL,
	`payment_amount` DECIMAL(24,2) NOT NULL DEFAULT 0.00,
	`gateway_callback_url` VARCHAR(191) NOT NULL DEFAULT NULL,
	`success_hook` VARCHAR(100) NOT NULL DEFAULT NULL,
	`failure_hook` VARCHAR(100) NOT NULL DEFAULT NULL,
	`transaction_id` VARCHAR(100) NOT NULL DEFAULT NULL,
	`currency_code` VARCHAR(20) NOT NULL DEFAULT 'USD',
	`payment_method` VARCHAR(50) NOT NULL DEFAULT NULL,
	`additional_data` LONGTEXT NOT NULL,
	`is_paid` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`payer_information` LONGTEXT NOT NULL,
	`external_redirect_link` VARCHAR(255) NOT NULL DEFAULT NULL,
	`receiver_information` LONGTEXT NOT NULL,
	`attribute_id` VARCHAR(64) NOT NULL DEFAULT NULL,
	`attribute` VARCHAR(255) NOT NULL DEFAULT NULL,
	`payment_platform` VARCHAR(255) NOT NULL DEFAULT NULL
);


CREATE TABLE IF NOT EXISTS `paytabs_invoices` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`order_id` BIGINT NOT NULL,
	`result` TEXT NOT NULL,
	`response_code` INTEGER NOT NULL,
	`pt_invoice_id` INTEGER NOT NULL DEFAULT NULL,
	`amount` DOUBLE(8,2) NOT NULL DEFAULT NULL,
	`currency` VARCHAR(191) NOT NULL DEFAULT NULL,
	`transaction_id` INTEGER NOT NULL DEFAULT NULL,
	`card_brand` VARCHAR(191) NOT NULL DEFAULT NULL,
	`card_first_six_digits` INTEGER NOT NULL DEFAULT NULL,
	`card_last_four_digits` INTEGER NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `phone_or_email_verifications` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`phone_or_email` VARCHAR(191) NOT NULL DEFAULT NULL,
	`token` TEXT NOT NULL,
	`otp_hit_count` TINYINT NOT NULL DEFAULT 0,
	`is_temp_blocked` TINYINT NOT NULL DEFAULT 0,
	`temp_block_time` TIMESTAMP NOT NULL DEFAULT NULL,
	`expires_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `product_seos` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`product_id` INTEGER NOT NULL,
	`title` VARCHAR(255) NOT NULL DEFAULT NULL,
	`description` VARCHAR(255) NOT NULL DEFAULT NULL,
	`index` VARCHAR(255) NOT NULL DEFAULT NULL,
	`no_follow` VARCHAR(255) NOT NULL DEFAULT NULL,
	`no_image_index` VARCHAR(255) NOT NULL DEFAULT NULL,
	`no_archive` VARCHAR(255) NOT NULL DEFAULT NULL,
	`no_snippet` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_snippet` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_snippet_value` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_video_preview` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_video_preview_value` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_image_preview` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_image_preview_value` VARCHAR(255) NOT NULL DEFAULT NULL,
	`image` VARCHAR(255) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `product_stocks` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`product_id` BIGINT NOT NULL DEFAULT NULL,
	`variant` VARCHAR(255) NOT NULL DEFAULT NULL,
	`sku` VARCHAR(255) NOT NULL DEFAULT NULL,
	`price` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
	`qty` INTEGER NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `product_tag` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`product_id` BIGINT NOT NULL,
	`tag_id` BIGINT NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `products` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`added_by` VARCHAR(191) NOT NULL DEFAULT NULL,
	`user_id` BIGINT NOT NULL DEFAULT NULL,
	`name` VARCHAR(80) NOT NULL DEFAULT NULL,
	`slug` VARCHAR(120) NOT NULL DEFAULT NULL,
	`product_type` VARCHAR(20) NOT NULL DEFAULT 'physical',
	`category_ids` VARCHAR(80) NOT NULL DEFAULT NULL,
	`category_id` VARCHAR(191) NOT NULL DEFAULT NULL,
	`sub_category_id` VARCHAR(191) NOT NULL DEFAULT NULL,
	`sub_sub_category_id` VARCHAR(191) NOT NULL DEFAULT NULL,
	`brand_id` BIGINT NOT NULL DEFAULT NULL,
	`unit` VARCHAR(191) NOT NULL DEFAULT NULL,
	`min_qty` INTEGER NOT NULL DEFAULT 1,
	`refundable` TINYINT NOT NULL DEFAULT 1,
	`digital_product_type` VARCHAR(30) NOT NULL DEFAULT NULL,
	`digital_file_ready` VARCHAR(191) NOT NULL DEFAULT NULL,
	`digital_file_ready_storage_type` VARCHAR(10) NOT NULL DEFAULT 'public',
	`images` LONGTEXT NOT NULL,
	`color_image` TEXT NOT NULL,
	`thumbnail` VARCHAR(255) NOT NULL DEFAULT NULL,
	`thumbnail_storage_type` VARCHAR(10) NOT NULL DEFAULT 'public',
	`preview_file` VARCHAR(255) NOT NULL DEFAULT NULL,
	`preview_file_storage_type` VARCHAR(255) NOT NULL DEFAULT 'public',
	`featured` VARCHAR(255) NOT NULL DEFAULT NULL,
	`flash_deal` VARCHAR(255) NOT NULL DEFAULT NULL,
	`video_provider` VARCHAR(30) NOT NULL DEFAULT NULL,
	`video_url` VARCHAR(150) NOT NULL DEFAULT NULL,
	`colors` VARCHAR(150) NOT NULL DEFAULT NULL,
	`variant_product` TINYINT NOT NULL DEFAULT 0,
	`attributes` VARCHAR(255) NOT NULL DEFAULT NULL,
	`choice_options` TEXT NOT NULL,
	`variation` TEXT NOT NULL,
	`digital_product_file_types` LONGTEXT NOT NULL,
	`digital_product_extensions` LONGTEXT NOT NULL,
	`published` TINYINT NOT NULL DEFAULT 0,
	`unit_price` DOUBLE NOT NULL DEFAULT 0,
	`purchase_price` DOUBLE NOT NULL DEFAULT 0,
	`tax` VARCHAR(191) NOT NULL DEFAULT '0.00',
	`tax_type` VARCHAR(80) NOT NULL DEFAULT NULL,
	`tax_model` VARCHAR(20) NOT NULL DEFAULT 'exclude',
	`discount` VARCHAR(191) NOT NULL DEFAULT '0.00',
	`discount_type` VARCHAR(80) NOT NULL DEFAULT NULL,
	`current_stock` INTEGER NOT NULL DEFAULT NULL,
	`minimum_order_qty` INTEGER NOT NULL DEFAULT 1,
	`details` TEXT NOT NULL,
	`free_shipping` TINYINT NOT NULL DEFAULT 0,
	`attachment` VARCHAR(191) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`status` TINYINT NOT NULL DEFAULT 1,
	`featured_status` TINYINT NOT NULL DEFAULT 1,
	`meta_title` VARCHAR(191) NOT NULL DEFAULT NULL,
	`meta_description` VARCHAR(191) NOT NULL DEFAULT NULL,
	`meta_image` VARCHAR(191) NOT NULL DEFAULT NULL,
	`request_status` TINYINT NOT NULL DEFAULT 0,
	`denied_note` TEXT NOT NULL,
	`shipping_cost` DOUBLE(8,2) NOT NULL DEFAULT NULL,
	`multiply_qty` TINYINT NOT NULL DEFAULT NULL,
	`temp_shipping_cost` DOUBLE(8,2) NOT NULL DEFAULT NULL,
	`is_shipping_cost_updated` TINYINT NOT NULL DEFAULT NULL,
	`code` VARCHAR(191) NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `publishing_houses` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `recent_searches` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT NOT NULL DEFAULT NULL,
	`user_type` VARCHAR(255) NOT NULL DEFAULT NULL,
	`title` VARCHAR(255) NOT NULL DEFAULT NULL,
	`route_uri` VARCHAR(255) NOT NULL DEFAULT NULL,
	`route_full_url` VARCHAR(255) NOT NULL DEFAULT NULL,
	`keyword` VARCHAR(255) NOT NULL DEFAULT NULL,
	`response` JSON NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `referral_customers` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT NOT NULL,
	`refer_by` BIGINT NOT NULL,
	`ref_by_earning_amount` DOUBLE NOT NULL DEFAULT 0,
	`customer_discount_amount` DOUBLE NOT NULL DEFAULT 0,
	`customer_discount_amount_type` VARCHAR(255) NOT NULL DEFAULT NULL,
	`customer_discount_validity` INTEGER NOT NULL DEFAULT 0,
	`customer_discount_validity_type` VARCHAR(255) NOT NULL DEFAULT NULL,
	`registered_notify` TINYINT NOT NULL DEFAULT 0,
	`ordered_notify` TINYINT NOT NULL DEFAULT 0,
	`delivered_notify` TINYINT NOT NULL DEFAULT 0,
	`is_used` TINYINT NOT NULL DEFAULT 0,
	`is_used_by_refer` TINYINT NOT NULL DEFAULT 0,
	`is_checked` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `refund_requests` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`order_details_id` BIGINT NOT NULL,
	`customer_id` BIGINT NOT NULL,
	`status` VARCHAR(191) NOT NULL,
	`approved_count` TINYINT NOT NULL DEFAULT 0,
	`denied_count` TINYINT NOT NULL DEFAULT 0,
	`amount` DOUBLE(8,2) NOT NULL,
	`product_id` BIGINT NOT NULL,
	`order_id` BIGINT NOT NULL,
	`refund_reason` LONGTEXT NOT NULL,
	`images` TEXT NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`approved_note` LONGTEXT NOT NULL,
	`rejected_note` LONGTEXT NOT NULL,
	`payment_info` LONGTEXT NOT NULL,
	`change_by` VARCHAR(191) NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `refund_statuses` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`refund_request_id` BIGINT NOT NULL DEFAULT NULL,
	`change_by` VARCHAR(191) NOT NULL DEFAULT NULL,
	`change_by_id` BIGINT NOT NULL DEFAULT NULL,
	`status` VARCHAR(191) NOT NULL DEFAULT NULL,
	`message` LONGTEXT NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `refund_transactions` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`order_id` BIGINT NOT NULL DEFAULT NULL,
	`payment_for` VARCHAR(191) NOT NULL DEFAULT NULL,
	`payer_id` BIGINT NOT NULL DEFAULT NULL,
	`payment_receiver_id` BIGINT NOT NULL DEFAULT NULL,
	`paid_by` VARCHAR(191) NOT NULL DEFAULT NULL,
	`paid_to` VARCHAR(191) NOT NULL DEFAULT NULL,
	`payment_method` VARCHAR(191) NOT NULL DEFAULT NULL,
	`payment_status` VARCHAR(191) NOT NULL DEFAULT NULL,
	`amount` DOUBLE(8,2) NOT NULL DEFAULT NULL,
	`transaction_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`order_details_id` BIGINT NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`refund_id` BIGINT NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `restock_product_customers` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`restock_product_id` INTEGER NOT NULL,
	`customer_id` INTEGER NOT NULL DEFAULT NULL,
	`variant` VARCHAR(255) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `restock_products` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`product_id` INTEGER NOT NULL,
	`variant` VARCHAR(255) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `review_replies` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`review_id` INTEGER NOT NULL,
	`added_by_id` INTEGER NOT NULL DEFAULT NULL,
	`added_by` VARCHAR(255) NOT NULL COMMENT 'customer, seller, admin, deliveryman',
	`reply_text` TEXT NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `reviews` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`product_id` BIGINT NOT NULL,
	`customer_id` BIGINT NOT NULL,
	`delivery_man_id` BIGINT NOT NULL DEFAULT NULL,
	`order_id` BIGINT NOT NULL DEFAULT NULL,
	`comment` MEDIUMTEXT NOT NULL,
	`attachment` LONGTEXT NOT NULL,
	`rating` INTEGER NOT NULL DEFAULT 0,
	`status` INTEGER NOT NULL DEFAULT 1,
	`is_saved` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `robots_meta_contents` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`page_title` VARCHAR(255) NOT NULL DEFAULT NULL,
	`page_name` VARCHAR(255) NOT NULL DEFAULT NULL,
	`page_url` VARCHAR(255) NOT NULL DEFAULT NULL,
	`meta_title` VARCHAR(255) NOT NULL DEFAULT NULL,
	`meta_description` TEXT NOT NULL,
	`meta_image` VARCHAR(255) NOT NULL DEFAULT NULL,
	`canonicals_url` VARCHAR(255) NOT NULL DEFAULT NULL,
	`index` VARCHAR(255) NOT NULL DEFAULT NULL,
	`no_follow` VARCHAR(255) NOT NULL DEFAULT NULL,
	`no_image_index` VARCHAR(255) NOT NULL DEFAULT NULL,
	`no_archive` VARCHAR(255) NOT NULL DEFAULT NULL,
	`no_snippet` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_snippet` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_snippet_value` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_video_preview` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_video_preview_value` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_image_preview` VARCHAR(255) NOT NULL DEFAULT NULL,
	`max_image_preview_value` VARCHAR(255) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `search_functions` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`key` VARCHAR(150) NOT NULL DEFAULT NULL,
	`url` VARCHAR(250) NOT NULL DEFAULT NULL,
	`visible_for` VARCHAR(191) NOT NULL DEFAULT 'admin',
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `shipping_addresses` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`customer_id` VARCHAR(15) NOT NULL DEFAULT NULL,
	`is_guest` TINYINT NOT NULL DEFAULT 0,
	`contact_person_name` VARCHAR(50) NOT NULL DEFAULT NULL,
	`email` VARCHAR(255) NOT NULL DEFAULT NULL,
	`address_type` VARCHAR(20) NOT NULL DEFAULT 'home',
	`address` VARCHAR(255) NOT NULL DEFAULT NULL,
	`city` VARCHAR(50) NOT NULL DEFAULT NULL,
	`zip` VARCHAR(10) NOT NULL DEFAULT NULL,
	`phone` VARCHAR(20) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`state` VARCHAR(191) NOT NULL DEFAULT NULL,
	`country` VARCHAR(191) NOT NULL DEFAULT NULL,
	`latitude` VARCHAR(191) NOT NULL DEFAULT NULL,
	`longitude` VARCHAR(191) NOT NULL DEFAULT NULL,
	`is_billing` TINYINT NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `shipping_methods` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`creator_id` BIGINT NOT NULL DEFAULT NULL,
	`creator_type` VARCHAR(191) NOT NULL DEFAULT 'admin',
	`title` VARCHAR(100) NOT NULL DEFAULT NULL,
	`cost` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
	`duration` VARCHAR(20) NOT NULL DEFAULT NULL,
	`status` TINYINT NOT NULL DEFAULT 1,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `shipping_types` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`seller_id` BIGINT NOT NULL DEFAULT NULL,
	`shipping_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `shop_followers` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`shop_id` INTEGER NOT NULL,
	`user_id` INTEGER NOT NULL COMMENT 'Customer ID',
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `shops` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`seller_id` BIGINT NOT NULL,
	`name` VARCHAR(100) NOT NULL,
	`slug` VARCHAR(191) NOT NULL DEFAULT 'en',
	`address` VARCHAR(255) NOT NULL,
	`contact` VARCHAR(25) NOT NULL,
	`image` VARCHAR(30) NOT NULL DEFAULT 'def.png',
	`image_storage_type` VARCHAR(10) NOT NULL DEFAULT 'public',
	`bottom_banner` VARCHAR(191) NOT NULL DEFAULT NULL,
	`bottom_banner_storage_type` VARCHAR(10) NOT NULL DEFAULT 'public',
	`offer_banner` VARCHAR(255) NOT NULL DEFAULT NULL,
	`offer_banner_storage_type` VARCHAR(10) NOT NULL DEFAULT 'public',
	`vacation_start_date` DATETIME NOT NULL DEFAULT NULL,
	`vacation_end_date` DATETIME NOT NULL DEFAULT NULL,
	`vacation_duration_type` VARCHAR(255) NOT NULL DEFAULT NULL,
	`vacation_note` VARCHAR(255) NOT NULL DEFAULT NULL,
	`vacation_status` TINYINT NOT NULL DEFAULT 0,
	`temporary_close` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`banner` VARCHAR(191) NOT NULL,
	`banner_storage_type` VARCHAR(10) NOT NULL DEFAULT 'public',
	`setup_guide` JSON NOT NULL,
	`tax_identification_number` VARCHAR(255) NOT NULL DEFAULT NULL,
	`tin_expire_date` DATE NOT NULL DEFAULT NULL,
	`tin_certificate` VARCHAR(255) NOT NULL DEFAULT NULL,
	`tin_certificate_storage_type` VARCHAR(255) NOT NULL DEFAULT 'public',
	`setup_guide_app` JSON NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `social_medias` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`link` VARCHAR(100) NOT NULL,
	`icon` VARCHAR(100) NOT NULL DEFAULT NULL,
	`active_status` INTEGER NOT NULL,
	`status` TINYINT NOT NULL DEFAULT 1,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `soft_credentials` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`key` VARCHAR(191) NOT NULL DEFAULT NULL,
	`value` LONGTEXT NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `stock_clearance_products` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`added_by` VARCHAR(255) NOT NULL,
	`product_id` INTEGER NOT NULL DEFAULT NULL,
	`setup_id` INTEGER NOT NULL DEFAULT NULL,
	`user_id` INTEGER NOT NULL DEFAULT NULL,
	`shop_id` INTEGER NOT NULL DEFAULT NULL,
	`is_active` TINYINT NOT NULL DEFAULT 0,
	`discount_type` VARCHAR(255) NOT NULL DEFAULT 'percentage',
	`discount_amount` DECIMAL(18,12) NOT NULL DEFAULT 0.000000000000,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `stock_clearance_setups` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`setup_by` VARCHAR(255) NOT NULL,
	`user_id` INTEGER NOT NULL DEFAULT NULL,
	`shop_id` INTEGER NOT NULL DEFAULT NULL,
	`is_active` TINYINT NOT NULL DEFAULT 0,
	`discount_type` VARCHAR(255) NOT NULL DEFAULT 'percentage',
	`discount_amount` DECIMAL(18,12) NOT NULL DEFAULT 0.000000000000,
	`offer_active_time` VARCHAR(255) NOT NULL DEFAULT NULL,
	`offer_active_range_start` TIME NOT NULL DEFAULT NULL,
	`offer_active_range_end` TIME NOT NULL DEFAULT NULL,
	`show_in_homepage` TINYINT NOT NULL DEFAULT 0,
	`show_in_homepage_once` TINYINT NOT NULL DEFAULT 0,
	`show_in_shop` TINYINT NOT NULL DEFAULT 1,
	`duration_start_date` TIMESTAMP NOT NULL DEFAULT NULL,
	`duration_end_date` TIMESTAMP NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `storages` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`data_type` VARCHAR(255) NOT NULL,
	`data_id` VARCHAR(100) NOT NULL,
	`key` VARCHAR(255) NOT NULL DEFAULT NULL,
	`value` VARCHAR(255) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `subscriptions` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(191) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `support_ticket_convs` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`support_ticket_id` BIGINT NOT NULL DEFAULT NULL,
	`admin_id` BIGINT NOT NULL DEFAULT NULL,
	`customer_message` VARCHAR(191) NOT NULL DEFAULT NULL,
	`attachment` LONGTEXT NOT NULL,
	`admin_message` VARCHAR(191) NOT NULL DEFAULT NULL,
	`position` INTEGER NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `support_tickets` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`customer_id` BIGINT NOT NULL DEFAULT NULL,
	`subject` VARCHAR(150) NOT NULL DEFAULT NULL,
	`type` VARCHAR(50) NOT NULL DEFAULT NULL,
	`priority` VARCHAR(15) NOT NULL DEFAULT 'low',
	`description` VARCHAR(255) NOT NULL DEFAULT NULL,
	`attachment` LONGTEXT NOT NULL,
	`reply` VARCHAR(255) NOT NULL DEFAULT NULL,
	`status` VARCHAR(15) NOT NULL DEFAULT 'open',
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `tags` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`tag` VARCHAR(191) NOT NULL,
	`visit_count` BIGINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `transactions` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`order_id` BIGINT NOT NULL DEFAULT NULL,
	`payment_for` VARCHAR(100) NOT NULL DEFAULT NULL,
	`payer_id` BIGINT NOT NULL DEFAULT NULL,
	`payment_receiver_id` BIGINT NOT NULL DEFAULT NULL,
	`paid_by` VARCHAR(15) NOT NULL DEFAULT NULL,
	`paid_to` VARCHAR(15) NOT NULL DEFAULT NULL,
	`payment_method` VARCHAR(15) NOT NULL DEFAULT NULL,
	`payment_status` VARCHAR(10) NOT NULL DEFAULT 'success',
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`amount` DOUBLE(8,2) NOT NULL DEFAULT 0.00,
	`transaction_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`order_details_id` BIGINT NOT NULL DEFAULT NULL,
	CONSTRAINT `transactions_id_unique` UNIQUE (`id`)
);


CREATE TABLE IF NOT EXISTS `translations` (
	`translationable_type` VARCHAR(191) NOT NULL,
	`translationable_id` BIGINT NOT NULL,
	`locale` VARCHAR(191) NOT NULL,
	`key` VARCHAR(191) NOT NULL DEFAULT NULL,
	`value` TEXT NOT NULL,
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `customers` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(80) NOT NULL DEFAULT NULL,
	`f_name` VARCHAR(255) NOT NULL DEFAULT NULL,
	`l_name` VARCHAR(255) NOT NULL DEFAULT NULL,
	`phone` VARCHAR(25) NOT NULL,
	`image` VARCHAR(30) NOT NULL DEFAULT 'def.png',
	`email` VARCHAR(255) NOT NULL DEFAULT NULL,
	`email_verified_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`password` VARCHAR(80) NOT NULL,
	`remember_token` VARCHAR(100) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`street_address` VARCHAR(250) NOT NULL DEFAULT NULL,
	`country` VARCHAR(50) NOT NULL DEFAULT NULL,
	`city` VARCHAR(50) NOT NULL DEFAULT NULL,
	`zip` VARCHAR(20) NOT NULL DEFAULT NULL,
	`house_no` VARCHAR(50) NOT NULL DEFAULT NULL,
	`apartment_no` VARCHAR(50) NOT NULL DEFAULT NULL,
	`cm_firebase_token` VARCHAR(191) NOT NULL DEFAULT NULL,
	`is_active` TINYINT NOT NULL DEFAULT 1,
	`payment_card_last_four` VARCHAR(191) NOT NULL DEFAULT NULL,
	`payment_card_brand` VARCHAR(191) NOT NULL DEFAULT NULL,
	`payment_card_fawry_token` TEXT NOT NULL,
	`login_medium` VARCHAR(191) NOT NULL DEFAULT NULL,
	`social_id` VARCHAR(191) NOT NULL DEFAULT NULL,
	`is_phone_verified` TINYINT NOT NULL DEFAULT 0,
	`temporary_token` VARCHAR(191) NOT NULL DEFAULT NULL,
	`is_email_verified` TINYINT NOT NULL DEFAULT 0,
	`wallet_balance` DECIMAL(18,12) NOT NULL DEFAULT NULL,
	`loyalty_point` DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
	`login_hit_count` TINYINT NOT NULL DEFAULT 0,
	`is_temp_blocked` TINYINT NOT NULL DEFAULT 0,
	`temp_block_time` TIMESTAMP NOT NULL DEFAULT NULL,
	`referral_code` VARCHAR(255) NOT NULL DEFAULT NULL,
	`referred_by` INTEGER NOT NULL DEFAULT NULL,
	`app_language` VARCHAR(191) NOT NULL DEFAULT 'en',
	PRIMARY KEY(`id`),
	CONSTRAINT `users_email_unique` UNIQUE (`email`)
);


CREATE TABLE IF NOT EXISTS `wallet_transactions` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT NOT NULL DEFAULT NULL,
	`transaction_id` CHAR(36) NOT NULL,
	`credit` DECIMAL(24,3) NOT NULL DEFAULT 0.000,
	`debit` DECIMAL(24,3) NOT NULL DEFAULT 0.000,
	`admin_bonus` DECIMAL(24,3) NOT NULL DEFAULT 0.000,
	`balance` DECIMAL(24,3) NOT NULL DEFAULT 0.000,
	`transaction_type` VARCHAR(191) NOT NULL DEFAULT NULL,
	`payment_method` VARCHAR(255) NOT NULL DEFAULT NULL,
	`reference` VARCHAR(191) NOT NULL DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `wishlists` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`customer_id` BIGINT NOT NULL,
	`product_id` BIGINT NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `withdraw_requests` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`seller_id` BIGINT NOT NULL DEFAULT NULL,
	`delivery_man_id` BIGINT NOT NULL DEFAULT NULL,
	`admin_id` BIGINT NOT NULL DEFAULT NULL,
	`amount` VARCHAR(191) NOT NULL DEFAULT '0.00',
	`withdrawal_method_id` BIGINT NOT NULL DEFAULT NULL,
	`withdrawal_method_fields` LONGTEXT NOT NULL,
	`transaction_note` TEXT NOT NULL,
	`approved` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `withdrawal_methods` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`method_name` VARCHAR(191) NOT NULL,
	`method_fields` TEXT NOT NULL,
	`is_default` TINYINT NOT NULL DEFAULT 0,
	`is_active` TINYINT NOT NULL DEFAULT 1,
	`created_at` TIMESTAMP NOT NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NOT NULL DEFAULT NULL,
	PRIMARY KEY(`id`)
);


